# logging settings
logging:
  level:
    root: info
    org:
      apache: warn
      quartz: warn
      springframework: warn

  pattern:
    # special characters need to be escaped / quoted
    console: '%clr([%date{HH:mm:ss.SSS}]){faint} %clr(%thread) %clr(%2p) %clr(%-40.40logger{36}){cyan} %m%n%wex'
simple:
  job:
    cron:
      # fires every 10 seconds
      expression: "*/10 * * * * ?"